repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: name-tests-test
        args: ['--pytest-test-first']
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
    -   id: nbqa-isort
        args: ["--float-to-top"]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: python
        types_or: [python, pyi]
        args: [--line-length=80]
    -   id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
        args: [--line-length=80]
    -   id: pytest
        name: pytest
        entry: pytest .
        args: [-vx]
        stages: [commit]
        language: system
        types: [python]
        require_serial: true
